(deffacts init (create)
	(maxduration 1000)
	(initial_agentstatus
		(pos-r 9) (pos-c 5)
		(direction south)
	)
) (deffacts initialmap(prior_cell (pos-r 1) (pos-c 1) (type border)) 
(prior_cell (pos-r 1) (pos-c 2) (type border)) 
(prior_cell (pos-r 1) (pos-c 3) (type border)) 
(prior_cell (pos-r 1) (pos-c 4) (type border)) 
(prior_cell (pos-r 1) (pos-c 5) (type gate)) 
(prior_cell (pos-r 1) (pos-c 6) (type border)) 
(prior_cell (pos-r 1) (pos-c 7) (type border)) 
(prior_cell (pos-r 1) (pos-c 8) (type border)) 
(prior_cell (pos-r 1) (pos-c 9) (type border)) 
(prior_cell (pos-r 2) (pos-c 1) (type border)) 
(prior_cell (pos-r 2) (pos-c 2) (type hill)) 
(prior_cell (pos-r 2) (pos-c 3) (type hill)) 
(prior_cell (pos-r 2) (pos-c 4) (type hill)) 
(prior_cell (pos-r 2) (pos-c 5) (type urban)) 
(prior_cell (pos-r 2) (pos-c 6) (type hill)) 
(prior_cell (pos-r 2) (pos-c 7) (type hill)) 
(prior_cell (pos-r 2) (pos-c 8) (type hill)) 
(prior_cell (pos-r 2) (pos-c 9) (type border)) 
(prior_cell (pos-r 3) (pos-c 1) (type border)) 
(prior_cell (pos-r 3) (pos-c 2) (type hill)) 
(prior_cell (pos-r 3) (pos-c 3) (type hill)) 
(prior_cell (pos-r 3) (pos-c 4) (type hill)) 
(prior_cell (pos-r 3) (pos-c 5) (type urban)) 
(prior_cell (pos-r 3) (pos-c 6) (type hill)) 
(prior_cell (pos-r 3) (pos-c 7) (type hill)) 
(prior_cell (pos-r 3) (pos-c 8) (type hill)) 
(prior_cell (pos-r 3) (pos-c 9) (type border)) 
(prior_cell (pos-r 4) (pos-c 1) (type border)) 
(prior_cell (pos-r 4) (pos-c 2) (type hill)) 
(prior_cell (pos-r 4) (pos-c 3) (type hill)) 
(prior_cell (pos-r 4) (pos-c 4) (type hill)) 
(prior_cell (pos-r 4) (pos-c 5) (type urban)) 
(prior_cell (pos-r 4) (pos-c 6) (type hill)) 
(prior_cell (pos-r 4) (pos-c 7) (type hill)) 
(prior_cell (pos-r 4) (pos-c 8) (type hill)) 
(prior_cell (pos-r 4) (pos-c 9) (type border)) 
(prior_cell (pos-r 5) (pos-c 1) (type gate)) 
(prior_cell (pos-r 5) (pos-c 2) (type urban)) 
(prior_cell (pos-r 5) (pos-c 3) (type urban)) 
(prior_cell (pos-r 5) (pos-c 4) (type urban)) 
(prior_cell (pos-r 5) (pos-c 5) (type urban)) 
(prior_cell (pos-r 5) (pos-c 6) (type urban)) 
(prior_cell (pos-r 5) (pos-c 7) (type urban)) 
(prior_cell (pos-r 5) (pos-c 8) (type urban)) 
(prior_cell (pos-r 5) (pos-c 9) (type gate)) 
(prior_cell (pos-r 6) (pos-c 1) (type border)) 
(prior_cell (pos-r 6) (pos-c 2) (type hill)) 
(prior_cell (pos-r 6) (pos-c 3) (type hill)) 
(prior_cell (pos-r 6) (pos-c 4) (type urban)) 
(prior_cell (pos-r 6) (pos-c 5) (type urban)) 
(prior_cell (pos-r 6) (pos-c 6) (type urban)) 
(prior_cell (pos-r 6) (pos-c 7) (type hill)) 
(prior_cell (pos-r 6) (pos-c 8) (type hill)) 
(prior_cell (pos-r 6) (pos-c 9) (type border)) 
(prior_cell (pos-r 7) (pos-c 1) (type border)) 
(prior_cell (pos-r 7) (pos-c 2) (type hill)) 
(prior_cell (pos-r 7) (pos-c 3) (type hill)) 
(prior_cell (pos-r 7) (pos-c 4) (type hill)) 
(prior_cell (pos-r 7) (pos-c 5) (type urban)) 
(prior_cell (pos-r 7) (pos-c 6) (type hill)) 
(prior_cell (pos-r 7) (pos-c 7) (type hill)) 
(prior_cell (pos-r 7) (pos-c 8) (type hill)) 
(prior_cell (pos-r 7) (pos-c 9) (type border)) 
(prior_cell (pos-r 8) (pos-c 1) (type border)) 
(prior_cell (pos-r 8) (pos-c 2) (type hill)) 
(prior_cell (pos-r 8) (pos-c 3) (type hill)) 
(prior_cell (pos-r 8) (pos-c 4) (type hill)) 
(prior_cell (pos-r 8) (pos-c 5) (type urban)) 
(prior_cell (pos-r 8) (pos-c 6) (type hill)) 
(prior_cell (pos-r 8) (pos-c 7) (type hill)) 
(prior_cell (pos-r 8) (pos-c 8) (type hill)) 
(prior_cell (pos-r 8) (pos-c 9) (type border)) 
(prior_cell (pos-r 9) (pos-c 1) (type border)) 
(prior_cell (pos-r 9) (pos-c 2) (type border)) 
(prior_cell (pos-r 9) (pos-c 3) (type border)) 
(prior_cell (pos-r 9) (pos-c 4) (type border)) 
(prior_cell (pos-r 9) (pos-c 5) (type gate)) 
(prior_cell (pos-r 9) (pos-c 6) (type border)) 
(prior_cell (pos-r 9) (pos-c 7) (type border)) 
(prior_cell (pos-r 9) (pos-c 8) (type border)) 
(prior_cell (pos-r 9) (pos-c 9) (type border)) 
)
